server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location /React-Components/ {
        try_files $uri $uri/ /React-Components/index.html;
    }

    location = / {
        return 301 /React-Components/;
    }

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1024;
}
